from langchain.tools import Tool
from langchain_community.tools import DuckDuckGoSearchRun
from utils.logger import Logger
from utils.supabase import supabase_client
logger = Logger(__file__) 
class StaticTools:
    def _web_search(query: str) -> str:
        """
        Search information in website. You can search anything if you need relevan information.
        
        Args:
            query: keyword to search on website
        """
        logger.info(f"Executing DuckDuckGo search with query: {query}")
        try:
            result = DuckDuckGoSearchRun().run(query)
            logger.info(f"Search completed successfully")
            return result
        except Exception as e:
            logger.error(f"Error during DuckDuckGo search: {str(e)}")
            raise

    tools = [_web_search]

class DynamicTools:
    def _access_task_db(query:str) -> str:
        """
        Execute posgresql query in supabase to table Task. You can do all function following this table detail:
        public.task (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id text NOT NULL DEFAULT ''::text,
            title text NOT NULL,
            description text NOT NULL,
            is_completed boolean NOT NULL,
            due_date text NOT NULL,
            priority int2 NOT NULL,
            created_at timestamp with time zone NOT NULL DEFAULT now(),
            updated_at timestamp without time zone NULL,
            CONSTRAINT task_pkey PRIMARY KEY (id)
        );

        the query is not support ";" character so please do not use it.

        Args:
            query: postgresql query to execute
        """
        return_msg = ""
        try:
            response = supabase_client.rpc("execute_raw_query", {"query": query}).execute()
            return_msg = "Success execute query."
            if response.data:
                return_msg = f"{return_msg}\n{str(response.data)}"
            return return_msg
        except Exception as e:
            return_msg = f"Failed to execute query with error: {e}"
            return return_msg
    
    def _access_issue_db(query:str) -> str:
        """
        Execute posgresql query in supabase to issues Task. You can do all function following this table detail:
        public.issues (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            title text NOT NULL,
            description text NOT NULL,
            status int2 NOT NULL,
            priority int2 NOT NULL,
            type int2 NOT NULL,
            reporter_id text NOT NULL,
            assignee_id text NOT NULL,
            due_date text NOT NULL,
            created_at timestamp with time zone NOT NULL DEFAULT now(),
            updated_at timestamp without time zone NULL,
            CONSTRAINT issues_pkey PRIMARY KEY (id)
        );

        the query is not support ";" character so please do not use it.

        Args:
            query: postgresql query to execute
        """
        return_msg = ""
        try:
            response = supabase_client.rpc("execute_raw_query", {"query": query}).execute()
            return_msg = "Success execute query."
            if response.data:
                return_msg = f"{return_msg}\n{str(response.data)}"
            return return_msg
        except Exception as e:
            return_msg = f"Failed to execute query with error: {e}"
            return return_msg


    tools = [_access_task_db, _access_issue_db]