from langchain_community.tools import DuckDuckGoSearchRun
from langgraph.prebuilt import InjectedState
from utils.logger import Logger
from utils.supabase import supabase_client
from discord.ext.commands import Context
from typing_extensions import Annotated
import discord
# from app import BOT
logger = Logger(__file__) 
class StaticTools:
    def _web_search(query: str) -> str:
        """
        Search information in website. You can search anything if you need relevan information.
        
        Args:
            query: keyword to search on website
        """
        logger.info(f"Executing DuckDuckGo search with query: {query}")
        try:
            result = DuckDuckGoSearchRun().run(query)
            logger.info(f"Search completed successfully")
            return result
        except Exception as e:
            logger.error(f"Error during DuckDuckGo search: {str(e)}")
            raise

    tools = [_web_search]

class DynamicTools:
    def _access_task_db(query:str) -> str:
        """
        Execute posgresql query in supabase to table Task. You can do all function following this table detail:
        public.task (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            user_id text NOT NULL DEFAULT ''::text,
            title text NOT NULL,
            description text NOT NULL,
            is_completed boolean NOT NULL,
            due_date text NOT NULL,
            priority int2 NOT NULL,
            created_at timestamp with time zone NOT NULL DEFAULT now(),
            updated_at timestamp without time zone NULL,
            CONSTRAINT task_pkey PRIMARY KEY (id)
        );

        the query is not support ";" character so please do not use it.

        Args:
            query: postgresql query to execute
        """
        return_msg = ""
        try:
            response = supabase_client.rpc("execute_raw_query", {"query": query}).execute()
            return_msg = "Success execute query."
            if response.data:
                return_msg = f"{return_msg}\n{str(response.data)}"
            return return_msg
        except Exception as e:
            return_msg = f"Failed to execute query with error: {e}"
            return return_msg
    
    def _access_issue_db(query:str) -> str:
        """
        Execute posgresql query in supabase to issues Task. You can do all function following this table detail:
        public.issues (
            id int4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            title text NOT NULL,
            description text NOT NULL,
            status int2 NOT NULL,
            priority int2 NOT NULL,
            type int2 NOT NULL,
            reporter_id text NOT NULL,
            assignee_id text NOT NULL,
            due_date text NOT NULL,
            created_at timestamp with time zone NOT NULL DEFAULT now(),
            updated_at timestamp without time zone NULL,
            CONSTRAINT issues_pkey PRIMARY KEY (id)
        );

        the query is not support ";" character so please do not use it.

        Args:
            query: postgresql query to execute
        """
        return_msg = ""
        try:
            response = supabase_client.rpc("execute_raw_query", {"query": query}).execute()
            return_msg = "Success execute query."
            if response.data:
                return_msg = f"{return_msg}\n{str(response.data)}"
            return return_msg
        except Exception as e:
            return_msg = f"Failed to execute query with error: {e}"
            return return_msg

    async def _create_issue_channel(channel_name:str, message:str, state: Annotated[dict, InjectedState]):
        """
        Create issue channel base on user request or user report. 
        This tool basicly execute after activity/tool of insert/input data to issue table.

        Args:
            channel_name: Name or title of the issue.
            message: Detail of the issue that would send to channel message.
        """
        CATEGORY_NAME = "Issue"

        # guild_context = BOT.get_guild(state["guild_id"])
        guild_context = {}
        category = discord.utils.get(guild_context.categories, name=CATEGORY_NAME)
        try:
            if not category:
                category = await guild_context.create_category(
                    name=CATEGORY_NAME,
                    position=0
                ) 

            channel = await guild_context.create_text_channel(
                name=channel_name,
                category=category,
            )
            channel.send(message)
            return f"Success create channel for ticket {channel_name}"
        except Exception as e:
            return f"Somethink went wrong: {e}"
        
    tools = [_access_task_db, _access_issue_db,]